### ISSUE TITLE
`Escalation` resources from `oncall.escalationChain.step.notifyOnCallFromSchedule` have invalid parameters

### ISSUE THREAD

**Issue by alexander-bauer** [grafana/grafana-crossplane-libsonnet#24]
Resources emitted from this function have mangled parameters.

```yaml
apiVersion: oncall.grafana.net.namespaced/v1alpha1
kind: Escalation
metadata:
  name: my-escalation
spec:
  parameters:
    forProvider:
      escalationChainRef:
        name: critical
      notifyOnCallFromScheduleRef:
        spec: # <-- nested spec should not be here; it should just be name
          parameters:
            forProvider:
              notifyOnCallFromScheduleRef:
                name: primary
      type: notify_on_call_from_schedule
```
