### ISSUE TITLE
`Integration`s created by `new()` are invalid

### ISSUE THREAD

**Issue by alexander-bauer** [grafana/grafana-crossplane-libsonnet#27]
In `0.5.0-0.22.0`, `Integration` resources created by `new()` are invalid due to the default route's `escalationChainRef` being defined at the top level, rather than under the `forProvider` object.

```yaml
apiVersion: oncall.grafana.net.namespaced/v1alpha1
escalationChainRef:
  name: default
kind: Integration
metadata:
  name: myIntegration
spec:
  parameters:
    forProvider:
      name: My Integration
      type: alertmanager
```
